# This is a basic workflow to help you get started with Actions

name: First work flow
on: workflow_dispatch
 jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
      - name: 
        run: echo Hello, world!
        - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
