# This is a basic workflow to help you get started with Actions

name: First work flow
on: 
  push:
  workflow_dispatch :
jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
       - name: read  reposity
         uses: actions/checkout@v2
       - name: see
         run: ls -l

       - name: single comment
         run: echo Hello, world!
       - name: Run a multi-line script
         run: |
          echo Add other actions to build,
          echo test, and deploy your project.
       - name: build dir and file test
         run: |
          mkdir buiid
          echo test, and deploy your project. > build/test.txt
